<?php

namespace App\Services;

use Carbon\Carbon;

class PdfReportService
{
    /**
     * Base CSS shared by all PDF reports.
     */
    private static function baseCss(): string
    {
        return '
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: "DejaVu Sans", Arial, sans-serif; font-size: 9px; padding: 20px; color: #1e293b; }
            .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 12px; margin-bottom: 15px; }
            .header h1 { font-size: 18px; color: #1e293b; font-weight: bold; }
            .header p { color: #64748b; font-size: 10px; margin-top: 4px; }
            .header .subtitle { font-size: 9px; color: #94a3b8; margin-top: 3px; }
            table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 8px; }
            th { background: #2563eb; color: white; padding: 6px 4px; text-align: center; font-weight: bold; border: 1px solid #1e40af; font-size: 8px; }
            td { padding: 5px 4px; border: 1px solid #d1d5db; text-align: center; font-size: 8px; }
            tr:nth-child(even) { background: #f8fafc; }
            .total-row { background: #e2e8f0; font-weight: bold; }
            .total-row td { border-top: 2px solid #2563eb; padding: 6px 4px; font-weight: bold; }
            .text-success { color: #059669; }
            .text-danger { color: #dc2626; }
            .text-right { text-align: right; }
            .text-left { text-align: left; }
            .text-center { text-align: center; }
            .footer { text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; margin-top: 15px; color: #94a3b8; font-size: 7px; }
            .empty { text-align: center; color: #94a3b8; padding: 20px; }
        ';
    }

    /**
     * Wrap content in the standard PDF shell.
     */
    private static function wrap(string $title, string $body, ?string $periodText = null): string
    {
        $period = $periodText ?? '';
        return '<!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>' . e($title) . '</title>
            <style>' . self::baseCss() . '</style>
        </head>
        <body>
            <div class="header">
                <h1>' . e(strtoupper($title)) . '</h1>
                <p>LGU Laguindingan - Fuel Consumption Monitoring System</p>
                <p class="subtitle">Generated: ' . now()->format('F d, Y h:i A') . '</p>
                ' . ($period ? '<p style="font-size:8px;color:#64748b;margin-top:3px;">' . e($period) . '</p>' : '') . '
            </div>
            ' . $body . '
            <div class="footer">
                <p>This report is automatically generated by the FCMS System</p>
                <p>© ' . date('Y') . ' Laguindingan Municipality - Fuel Consumption Monitoring System</p>
            </div>
        </body>
        </html>';
    }

    /**
     * Render a data table.
     */
    private static function table(array $headers, array $rows, ?array $totalRow = null): string
    {
        $html = '<table><thead><tr>';
        foreach ($headers as $h) {
            $html .= '<th>' . e($h) . '</th>';
        }
        $html .= '</tr></thead><tbody>';

        if (empty($rows)) {
            $html .= '<tr><td colspan="' . count($headers) . '" class="empty">No data available</td></tr>';
        } else {
            foreach ($rows as $row) {
                $html .= '<tr>';
                foreach ($row as $cell) {
                    $html .= '<td>' . $cell . '</td>';
                }
                $html .= '</tr>';
            }

            if ($totalRow) {
                $html .= '<tr class="total-row">';
                foreach ($totalRow as $cell) {
                    $html .= '<td>' . $cell . '</td>';
                }
                $html .= '</tr>';
            }
        }

        $html .= '</tbody></table>';
        return $html;
    }

    // ============================================================
    // VEHICLE SUMMARY
    // ============================================================
    public static function vehicleSummary(array $data, array $filters): string
    {
        $headers = ['Vehicle', 'Plate No.', 'Total Trips', 'Total Fuel (L)', 'Total Amount (₱)', 'Avg Fuel/Trip (L)'];
        $rows = [];
        $totalTrips = 0; $totalLiters = 0; $totalCost = 0;

        foreach ($data as $v) {
            $trips = (int) ($v['trip_count'] ?? 0);
            $liters = (float) ($v['total_liters'] ?? 0);
            $cost = (float) ($v['total_cost'] ?? 0);
            $avg = $trips > 0 ? $liters / $trips : 0;

            $totalTrips += $trips;
            $totalLiters += $liters;
            $totalCost += $cost;

            $rows[] = [
                e($v['model'] ?? 'N/A'),
                e($v['plate_number'] ?? 'N/A'),
                $trips,
                number_format($liters, 2),
                '₱' . number_format($cost, 2),
                number_format($avg, 2),
            ];
        }

        $avgTotal = $totalTrips > 0 ? $totalLiters / $totalTrips : 0;
        $totalRow = ['TOTAL', '', $totalTrips, number_format($totalLiters, 2), '₱' . number_format($totalCost, 2), number_format($avgTotal, 2)];

        $period = 'Period: ' . ($filters['start_date'] ?? 'N/A') . ' to ' . ($filters['end_date'] ?? 'N/A');
        return self::wrap('Vehicle Fuel Consumption Summary', self::table($headers, $rows, $totalRow), $period);
    }

    // ============================================================
    // DEPARTMENT SUMMARY
    // ============================================================
    public static function departmentSummary(array $data, array $filters): string
    {
        $depts = $data['departments'] ?? [];
        $headers = ['Department', 'Total Trips', 'Total Fuel (L)', 'Total Amount (₱)', 'Avg Fuel/Trip (L)'];
        $rows = [];
        $totalTrips = 0; $totalLiters = 0; $totalCost = 0;

        foreach ($depts as $d) {
            $trips = (int) ($d['total_trips'] ?? 0);
            $liters = (float) ($d['total_fuel_liters'] ?? 0);
            $cost = (float) ($d['total_amount'] ?? 0);
            $avg = $trips > 0 ? $liters / $trips : 0;

            $totalTrips += $trips;
            $totalLiters += $liters;
            $totalCost += $cost;

            $rows[] = [
                e($d['department_name'] ?? 'N/A'),
                $trips,
                number_format($liters, 2),
                '₱' . number_format($cost, 2),
                number_format($avg, 2),
            ];
        }

        $avgTotal = $totalTrips > 0 ? $totalLiters / $totalTrips : 0;
        $totalRow = ['TOTAL', $totalTrips, number_format($totalLiters, 2), '₱' . number_format($totalCost, 2), number_format($avgTotal, 2)];

        $period = 'Period: ' . ($filters['start_date'] ?? 'N/A') . ' to ' . ($filters['end_date'] ?? 'N/A');
        return self::wrap('Department Fuel Consumption Report', self::table($headers, $rows, $totalRow), $period);
    }

    // ============================================================
    // MONTHLY SUMMARY
    // ============================================================
    public static function monthlySummary(array $data, array $filters): string
    {
        $months = $data['months'] ?? [];
        $year = $data['summary']['year'] ?? date('Y');

        $headers = ['Month', 'Total Trips', 'Total Fuel (L)', 'Total Cost (₱)', 'Avg Fuel/Trip (L)'];
        $rows = [];
        $totalTrips = 0; $totalLiters = 0; $totalCost = 0;

        foreach ($months as $m) {
            $trips = (int) ($m['total_trips'] ?? 0);
            $liters = (float) ($m['total_fuel_liters'] ?? 0);
            $cost = (float) ($m['total_cost'] ?? 0);
            $avg = $trips > 0 ? $liters / $trips : 0;

            $totalTrips += $trips;
            $totalLiters += $liters;
            $totalCost += $cost;

            $rows[] = [
                e($m['month'] ?? 'N/A'),
                $trips,
                number_format($liters, 2),
                '₱' . number_format($cost, 2),
                number_format($avg, 2),
            ];
        }

        $avgTotal = $totalTrips > 0 ? $totalLiters / $totalTrips : 0;
        $totalRow = ['TOTAL', $totalTrips, number_format($totalLiters, 2), '₱' . number_format($totalCost, 2), number_format($avgTotal, 2)];

        return self::wrap('Monthly Fuel Consumption Summary', self::table($headers, $rows, $totalRow), 'Year: ' . $year);
    }

    // ============================================================
    // TRIP TICKET
    // ============================================================
    public static function tripTicket(array $data, array $filters): string
    {
        $trips = $data['trips'] ?? [];
        $headers = ['TT Number', 'Date', 'Department', 'Vehicle', 'Plate No.', 'Driver', 'Destination', 'Purpose', 'Distance (km)', 'Status'];
        $rows = [];

        foreach ($trips as $t) {
            $date = !empty($t['trip_date']) ? Carbon::parse($t['trip_date'])->format('m/d/Y') : 'N/A';
            $distance = $t['actual_distance_km'] ?? $t['estimated_distance_km'] ?? 0;

            $rows[] = [
                e($t['trip_ticket_number'] ?? 'N/A'),
                $date,
                e($t['department_name'] ?? 'N/A'),
                e($t['vehicle_model'] ?? 'N/A'),
                e($t['plate_number'] ?? 'N/A'),
                e($t['driver_name'] ?? 'N/A'),
                e($t['destination'] ?? 'N/A'),
                e($t['purpose'] ?? 'N/A'),
                number_format((float) $distance, 2),
                e(ucwords(str_replace('_', ' ', $t['status'] ?? 'N/A'))),
            ];
        }

        $period = 'Period: ' . ($filters['start_date'] ?? 'N/A') . ' to ' . ($filters['end_date'] ?? 'N/A');
        return self::wrap('Trip Ticket Report', self::table($headers, $rows), $period);
    }

    // ============================================================
    // GPS ACTIVITY
    // ============================================================
    public static function gpsActivity(array $data, array $filters): string
    {
        $activities = $data['activities'] ?? [];
        $headers = ['TT Number', 'Vehicle', 'Driver', 'Trip Start', 'Trip End', 'Duration (hrs)', 'GPS Distance', 'Logbook Distance', 'Match', 'Status'];
        $rows = [];

        foreach ($activities as $a) {
            $rows[] = [
                e($a['trip_ticket_number'] ?? 'N/A'),
                e($a['vehicle'] ?? 'N/A'),
                e($a['driver'] ?? 'N/A'),
                e($a['trip_start'] ?? 'N/A'),
                e($a['trip_end'] ?? 'N/A'),
                $a['duration_hrs'] ?? '—',
                number_format((float) ($a['gps_distance_km'] ?? 0), 2),
                number_format((float) ($a['logbook_distance_km'] ?? 0), 2),
                e($a['distance_match'] ?? 'N/A'),
                e($a['trip_status'] ?? 'N/A'),
            ];
        }

        $period = 'Period: ' . ($filters['start_date'] ?? 'N/A') . ' to ' . ($filters['end_date'] ?? 'N/A');
        return self::wrap('GPS Vehicle Activity Report', self::table($headers, $rows), $period);
    }

    // ============================================================
    // RECONCILIATION
    // ============================================================
    public static function reconciliation(array $data, array $filters): string
    {
        $reconciliations = $data['reconciliations'] ?? [];
        $headers = ['TT Number', 'Vehicle', 'Driver', 'Amount Released', 'Estimated Fuel', 'Actual Fuel', 'Variance', 'Status'];
        $rows = [];
        $totalAmount = 0; $totalEstimated = 0; $totalActual = 0;

        foreach ($reconciliations as $r) {
            $amount = (float) ($r['amount_released'] ?? 0);
            $est = (float) ($r['estimated_fuel'] ?? 0);
            $act = (float) ($r['actual_fuel'] ?? 0);
            $var = (float) ($r['variance'] ?? 0);

            $totalAmount += $amount;
            $totalEstimated += $est;
            $totalActual += $act;

            $varColor = abs($var) > 2 ? 'text-danger' : 'text-success';

            $rows[] = [
                e($r['ticket_number'] ?? 'N/A'),
                e($r['plate_number'] ?? 'N/A'),
                e($r['driver_name'] ?? 'N/A'),
                '₱' . number_format($amount, 2),
                number_format($est, 2),
                number_format($act, 2),
                '<span class="' . $varColor . '">' . number_format($var, 2) . '</span>',
                e(ucfirst($r['status'] ?? 'pending')),
            ];
        }

        $totalRow = ['TOTAL', '', '', '₱' . number_format($totalAmount, 2), number_format($totalEstimated, 2), number_format($totalActual, 2), '', ''];
        $period = 'Period: ' . ($filters['start_date'] ?? 'N/A') . ' to ' . ($filters['end_date'] ?? 'N/A');
        return self::wrap('Trip and Fuel Reconciliation Report', self::table($headers, $rows, $totalRow), $period);
    }

    // ============================================================
    // DRIVER EFFICIENCY
    // ============================================================
    public static function driverEfficiency(array $data, array $filters): string
    {
        $drivers = $data['drivers'] ?? [];
        $headers = ['Rank', 'Driver', 'Assigned Vehicle', 'Total Trips', 'Distance (km)', 'Fuel Used (L)', 'Efficiency (km/L)'];
        $rows = [];
        $rank = 1;
        $totalTrips = 0; $totalDistance = 0; $totalFuel = 0;

        foreach ($drivers as $d) {
            $trips = (int) ($d['total_trips'] ?? 0);
            $dist = (float) ($d['total_distance_km'] ?? 0);
            $fuel = (float) ($d['total_fuel_used_liters'] ?? 0);
            $eff = (float) ($d['fuel_efficiency_kmpl'] ?? 0);

            $totalTrips += $trips;
            $totalDistance += $dist;
            $totalFuel += $fuel;

            $rows[] = [
                $rank++,
                e($d['driver_name'] ?? 'N/A'),
                e($d['assigned_vehicle'] ?? 'N/A'),
                $trips,
                number_format($dist, 2),
                number_format($fuel, 2),
                number_format($eff, 2),
            ];
        }

        $avgEff = $totalFuel > 0 ? $totalDistance / $totalFuel : 0;
        $totalRow = ['', 'TOTAL', '', $totalTrips, number_format($totalDistance, 2), number_format($totalFuel, 2), number_format($avgEff, 2)];

        $period = 'Period: ' . ($filters['start_date'] ?? 'N/A') . ' to ' . ($filters['end_date'] ?? 'N/A');
        return self::wrap('Driver Fuel Efficiency Report', self::table($headers, $rows, $totalRow), $period);
    }

    // ============================================================
    // AUDIT TRAIL
    // ============================================================
    public static function auditTrail(array $data, array $filters): string
    {
        $logs = $data['logs'] ?? [];
        $headers = ['Date/Time', 'User', 'Role', 'Module', 'Action', 'Details', 'Result'];
        $rows = [];

        foreach ($logs as $log) {
            $createdAt = !empty($log['created_at']) ? Carbon::parse($log['created_at'])->format('m/d/Y H:i') : 'N/A';
            $result = $log['result'] ?? 'N/A';
            $resultColor = $result === 'Success' ? 'text-success' : 'text-danger';

            $rows[] = [
                $createdAt,
                e($log['user_name'] ?? 'N/A'),
                e($log['role'] ?? 'N/A'),
                e($log['module'] ?? 'N/A'),
                e($log['action'] ?? 'N/A'),
                e($log['details'] ?? 'N/A'),
                '<span class="' . $resultColor . '">' . e($result) . '</span>',
            ];
        }

        $period = 'Period: ' . ($filters['start_date'] ?? 'N/A') . ' to ' . ($filters['end_date'] ?? 'N/A');
        return self::wrap('Audit Trail Report', self::table($headers, $rows), $period);
    }

   // ============================================================
// BUDGET UTILIZATION
// ============================================================
public static function budgetUtilization(array $data, array $filters): string
{
    $department = $data['department'] ?? [];
    $summary    = $data['summary'] ?? [];
    $periods    = $data['periods'] ?? [];
    $filterData = $data['filters'] ?? $filters;

    $deptName   = $department['department_name'] ?? 'Unknown';
    $deptCode   = $department['department_code'] ?? 'N/A';
    $year       = $filterData['year'] ?? $filters['year'] ?? date('Y');
    $month      = $filterData['month'] ?? null;
    $monthLabel = $month
        ? Carbon::create()->month((int) $month)->format('F')
        : 'All Months';

    // ---- Summary cards block ----
    $summaryHtml = '
        <table style="margin-top: 0; margin-bottom: 14px; border-collapse: separate; border-spacing: 6px;">
            <tr>
                <td style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 10px; text-align: center; width: 25%;">
                    <div style="font-size: 8px; color: #1e40af; text-transform: uppercase; letter-spacing: 0.5px;">Annual Allocated</div>
                    <div style="font-size: 12px; font-weight: bold; color: #0f172a; margin-top: 4px;">₱' . number_format($summary['total_allocated'] ?? 0, 2) . '</div>
                </td>
                <td style="background: #fef3c7; border: 1px solid #fde68a; border-radius: 6px; padding: 10px; text-align: center; width: 25%;">
                    <div style="font-size: 8px; color: #92400e; text-transform: uppercase; letter-spacing: 0.5px;">Annual Utilized</div>
                    <div style="font-size: 12px; font-weight: bold; color: #0f172a; margin-top: 4px;">₱' . number_format($summary['total_used'] ?? 0, 2) . '</div>
                </td>
                <td style="background: #ecfdf5; border: 1px solid #a7f3d0; border-radius: 6px; padding: 10px; text-align: center; width: 25%;">
                    <div style="font-size: 8px; color: #065f46; text-transform: uppercase; letter-spacing: 0.5px;">Annual Remaining</div>
                    <div style="font-size: 12px; font-weight: bold; color: #0f172a; margin-top: 4px;">₱' . number_format($summary['total_remaining'] ?? 0, 2) . '</div>
                </td>
                <td style="background: #f3e8ff; border: 1px solid #ddd6fe; border-radius: 6px; padding: 10px; text-align: center; width: 25%;">
                    <div style="font-size: 8px; color: #5b21b6; text-transform: uppercase; letter-spacing: 0.5px;">Weeks in View</div>
                    <div style="font-size: 12px; font-weight: bold; color: #0f172a; margin-top: 4px;">' . ($summary['total_weeks'] ?? 0) . '</div>
                </td>
            </tr>
        </table>';

    // ---- Detail table ----
    $headers = ['Week (Date Range)', 'Budget (₱)', 'Utilized (₱)', 'Balance (₱)'];
    $rows = [];

    foreach ($periods as $p) {
        $weekStart = $p['week_start'] ?? null;
        $weekEnd   = $p['week_end'] ?? null;

        $range = '—';
        if ($weekStart && $weekEnd) {
            try {
                $range = Carbon::parse($weekStart)->format('M d, Y')
                       . ' – '
                       . Carbon::parse($weekEnd)->format('M d, Y');
            } catch (\Exception $e) {
                $range = $weekStart . ' – ' . $weekEnd;
            }
        }

        $rows[] = [
            e($range),
            '₱' . number_format((float) ($p['allocated'] ?? 0), 2),
            '₱' . number_format((float) ($p['used'] ?? 0), 2),
            '₱' . number_format((float) ($p['remaining'] ?? 0), 2),
        ];
    }

    // ---- TOTAL row (matches the frontend table logic) ----
    $totalRow = null;
    if (!empty($periods)) {
        $firstAllocated = (float) ($periods[0]['allocated'] ?? 0);
        $sumUsed        = array_sum(array_map(fn($p) => (float) ($p['used'] ?? 0), $periods));
        $lastRemaining  = (float) ($periods[count($periods) - 1]['remaining'] ?? 0);

        $totalRow = [
            'TOTAL',
            '₱' . number_format($firstAllocated, 2),
            '₱' . number_format($sumUsed, 2),
            '₱' . number_format($lastRemaining, 2),
        ];
    }

    $detailTable = self::table($headers, $rows, $totalRow);

    $period = $deptName . ' (' . $deptCode . ')  |  Year: ' . $year . '  |  ' . $monthLabel;

    return self::wrap('Budget Utilization Report', $summaryHtml . $detailTable, $period);
}
}